# Generated by Django 4.1.4 on 2022-12-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzasite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingridients',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='pizza',
            name='image',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
