# Generated by Django 4.1.4 on 2022-12-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzasite', '0003_remove_cart_pizza_cart_pizza'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_pizza', models.CharField(max_length=50)),
                ('radius', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
            options={
                'ordering': ['radius'],
            },
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='dough',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='ingridients',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='radius',
        ),
        migrations.AlterField(
            model_name='pizza',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Dough',
        ),
        migrations.DeleteModel(
            name='Ingridients',
        ),
        migrations.DeleteModel(
            name='Radius',
        ),
        migrations.AddField(
            model_name='pizza',
            name='price',
            field=models.ManyToManyField(to='pizzasite.price'),
        ),
    ]
