# Generated by Django 4.1.4 on 2022-12-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzasite', '0006_pizza_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('additional_payment', models.IntegerField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ['name_of_pizza', 'radius']},
        ),
        migrations.AddField(
            model_name='pizza',
            name='dough',
            field=models.ManyToManyField(to='pizzasite.dough'),
        ),
    ]
