# Generated by Django 4.1.4 on 2023-01-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzasite', '0009_cart_img_cart_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='main_price',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
