# Generated by Django 4.1.4 on 2023-01-07 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzasite', '0011_alter_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
