# Generated by Django 4.1.4 on 2023-01-07 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzasite', '0015_sessionuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessionuser',
            name='session_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
