# Generated by Django 4.1.4 on 2023-01-10 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzasite', '0018_order_commentary_order_is_finished_order_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_finished',
            field=models.BooleanField(default=False),
        ),
    ]
