# Generated by Django 4.1.4 on 2022-12-26 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_myuser_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='cart',
        ),
    ]
