# Generated by Django 4.1.4 on 2023-01-05 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_remove_myuser_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='cart_price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
