# Generated by Django 4.1.4 on 2023-01-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_myuser_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='cart_price',
            field=models.CharField(max_length=100),
        ),
    ]
